version: 2

jobs:
  run-tests:
    docker:
      - image: python:3.6
    steps:
      - checkout

      - run:
          name: Install requirements
          command: pip install -r requirements.txt

      - run:
          name: Install bleeding edge prefect
          command: pip install -U git+https://github.com/PrefectHQ/prefect.git@master

      - run:
          name: Install GeoCity DB
          command: |
            curl -fL https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz -o ~/geocities.tar.gz
            cd ~
            tar -xzf geocities.tar.gz # creates file ~/GeoLite2-City_20191001/GeoLite2-City.mmdb
            mv GeoLite* GeoLite/

      - run:
          name: Run tests
          command: pytest -rfEsx

workflows:
  version: 2

  "Run tests":
    jobs:
      - run-tests
